export const appCopy = {
  ar: {
    dir: "rtl",
    title: "لوحة Remindo",
    subtitle: "تذكيراتك محفوظة في حسابك وتُرسل في وقتها.",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    name: "الاسم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    timezone: "المنطقة الزمنية",
    submit: "متابعة",
    logout: "تسجيل الخروج",
    reminders: "التذكيرات",
    empty: "لا توجد تذكيرات بعد.",
    add: "إضافة تذكير",
    reminderName: "اسم التذكير",
    expiry: "تاريخ الانتهاء",
    notificationAt: "وقت التنبيه",
    channel: "القناة",
    save: "حفظ وجدولة",
    loading: "جارٍ التحميل…",
    error: "تعذر إكمال الطلب.",
  },
  en: {
    dir: "ltr",
    title: "Remindo dashboard",
    subtitle: "Your reminders are stored in your account and sent on schedule.",
    login: "Sign in",
    register: "Create account",
    name: "Name",
    email: "Email",
    password: "Password",
    timezone: "Timezone",
    submit: "Continue",
    logout: "Sign out",
    reminders: "Reminders",
    empty: "No reminders yet.",
    add: "Add reminder",
    reminderName: "Reminder name",
    expiry: "Expiration date",
    notificationAt: "Notification time",
    channel: "Channel",
    save: "Save and schedule",
    loading: "Loading…",
    error: "The request could not be completed.",
  },
} as const;
