export const appCopy = {
  ar: {
    dir: "rtl", title: "لوحة Remindo", subtitle: "كل مواعيدك المهمة في مكان واحد.",
    login: "تسجيل الدخول", register: "إنشاء حساب", demo: "تجربة الحساب التجريبي",
    name: "الاسم", email: "البريد الإلكتروني", password: "كلمة المرور", timezone: "المنطقة الزمنية",
    submit: "متابعة", logout: "تسجيل الخروج", loading: "جارٍ التحميل…", error: "تعذر إكمال الطلب.",
    nav: ["نظرة عامة", "التذكيرات", "التقويم", "الإشعارات", "الاشتراك", "الإعدادات"],
    overview: "نظرة عامة", welcome: "أهلًا", active: "نشط", seven: "خلال 7 أيام", thirty: "خلال 30 يومًا", overdue: "متأخر",
    upcoming: "أقرب التذكيرات", activity: "النشاط الأخير", empty: "لا توجد بيانات بعد.",
    reminders: "التذكيرات", add: "إضافة تذكير", edit: "تعديل", snooze: "تأجيل يوم", complete: "تم الإنجاز", renew: "تجديد سنة", remove: "حذف",
    reminderName: "اسم التذكير", expiry: "تاريخ الانتهاء", notificationAt: "وقت التنبيه", channel: "القناة",
    schedules: "مواعيد التنبيه", addSchedule: "إضافة موعد تنبيه", save: "حفظ", cancel: "إلغاء",
    calendar: "التقويم", notifications: "الإشعارات", markRead: "قراءة الكل", subscription: "الاشتراك",
    plan: "الباقة الحالية", usage: "استخدام التذكيرات", settings: "الإعدادات", phone: "الجوال",
    country: "الدولة", currency: "العملة", saveSettings: "حفظ الإعدادات", saved: "تم الحفظ بنجاح.",
  },
  en: {
    dir: "ltr", title: "Remindo dashboard", subtitle: "Every important date in one place.",
    login: "Sign in", register: "Create account", demo: "Try the demo account",
    name: "Name", email: "Email", password: "Password", timezone: "Timezone",
    submit: "Continue", logout: "Sign out", loading: "Loading…", error: "The request could not be completed.",
    nav: ["Overview", "Reminders", "Calendar", "Notifications", "Subscription", "Settings"],
    overview: "Overview", welcome: "Welcome", active: "Active", seven: "Due in 7 days", thirty: "Due in 30 days", overdue: "Overdue",
    upcoming: "Upcoming reminders", activity: "Recent activity", empty: "Nothing here yet.",
    reminders: "Reminders", add: "Add reminder", edit: "Edit", snooze: "Snooze 1 day", complete: "Complete", renew: "Renew 1 year", remove: "Delete",
    reminderName: "Reminder name", expiry: "Expiration date", notificationAt: "Notification time", channel: "Channel",
    schedules: "Notification schedules", addSchedule: "Add schedule", save: "Save", cancel: "Cancel",
    calendar: "Calendar", notifications: "Notifications", markRead: "Mark all read", subscription: "Subscription",
    plan: "Current plan", usage: "Reminder usage", settings: "Settings", phone: "Phone",
    country: "Country", currency: "Currency", saveSettings: "Save settings", saved: "Saved successfully.",
  },
} as const;
